### ISSUE TITLE
Additional keybindings

### ISSUE THREAD

**Issue by adam-mcdaniel** [rhysd/kiro-editor#1]
I think it would be very practical to be able to move lines up and down using a keybinding like CTRL+UpArrow/DownArrow.

Additionally CTRL+D or some other keybinding should be used to duplicate a line.

I tried to implement these features myself in a short period of time, but Im not very familiar with the structure of kiro.

**Comment by rhysd** [comment]
Please see README.md before creating an issue. They are already mapped.

https://github.com/rhysd/kiro-editor/blob/master/README.md#edit-text

**Comment by rhysd** [comment]
Closing as no response
