### ISSUE TITLE
kiro-editor packaged for NetBSD

### ISSUE THREAD

**Issue by voidpin** [rhysd/kiro-editor#7]
Just to let you know that `kiro` has now been packaged for NetBSD.

**Comment by rhysd** [comment]
Thank you for letting me know. Can you show some URL to the package information?

**Comment by voidpin** [comment]
Sure,
Online NetBSD pkg search, https://pkgsrc.se/editors/kiro-editor

Commit/merge info, https://mail-index.netbsd.org/pkgsrc-changes/2020/10/23/msg222988.html

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by rhysd** [comment]
OK, thanks! I'll add the link to README file.
